# 워크플로우 이름을 지정하는 부분이다.
name: crawlingPractice

# 어떠한 이벤트가 발생했을 때, 워크플로우를 실행시킬지 정한다.
# ex) push나 pull이 일어났을때, 또는 cron을 통해 일정주기마다 실행시킬지
on: [push]
#  schedule:
#    - cron: "*/10 * * * *"

# 워크플로우가 실행되면 수행될 동작을 정한다.
jobs:
  # 빌드 동작을 수행한다.
  build:
    # 빌드 동작이 수행될 환경을 지정한다.
    # ubuntu, mac os, windows 등의 github가 호스팅하는 머신환경을 이용할 수도 있고,
    # 사용자의 호스팅 환경이나, 도커 컨테이너등을 이용할 수도 있다.
    runs-on: ubuntu-latest
    # 실행할 여러 동작을 여기에 정의한다.
    steps:
      # 아래와 같이 actions에서 가져다 쓸 수 있다.
      - uses: actions/checkout@v2
        with:
          # 개인 토큰을 사용할 것인지 말 것인지
          persist-credentials: false
      - name: 1. pip 업그레이드
        run: python -m pip install --upgrade pip
      - name: 2. 필요한 패키지 인스톨
        run: pip install -r requirements.txt
      - name: 3. 크롤링 코드 실행
        run: |
          python crawler/mainDataCrawler.py
          python crawler/fetchDataCrawler.py
      - name: 4. 커밋
        run: |
          git config --local user.email "hdh1028@naver.com"
          git config --local user.name "HwangDoHyun28"
          git add .
          git commit -m "Run crawler and update current data"
      - name: 5. 푸시
        uses: ad-m/github-push-action@master
        with:
          # branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
